---
:concurrency: 5
:timeout: 25
:verbose: true
:queues:
  - [default, 1]
  - [critical, 5]

:scheduler:
  :schedule:
    fetch_github_events:
      cron: '*/5 * * * *'
      class: FetchGithubEventsJob
      queue: default